name: Get short commit SHA
inputs:
  terraform-plan-file-name:
    type: string
    description: The name of the Terraform plan file used for the comment
  terraform-plan-artifact-link:
    type: string
    description: The link to the build artifact containing the Terraform plan

runs:
  using: composite
  steps:
    - name: Trim terraform plan
      id: trim-terraform-plan
      shell: bash
      run: |
        set -x

        if terraform show -no-color "$TERRAFORM_PLAN_FILE_NAME" | grep "No changes. Your infrastructure matches the configuration."; then
          echo "No plan to format"
          exit 0
        fi

        terraform show -no-color "$TERRAFORM_PLAN_FILE_NAME" | awk '/Terraform will perform the following actions:/{flag=1; next} flag' >> tfplan_short

        numbers=$(cat tfplan_short | grep -oP 'Plan: (\d+ to add, \d+ to change, \d+ to destroy.)' | awk '{print $2, $5, $8}')
        add=$(echo "$numbers" | cut -d " " -f 1)
        change=$(echo "$numbers" | cut -d " " -f 2)
        destroy=$(echo "$numbers" | cut -d " " -f 3)

        # Mark additions 
        sed -i 's/\(^\s*\)+/+&/' tfplan_short
        # Mark changes 
        sed -i 's/\(^\s*\)~/!&/' tfplan_short
        # Mark destructions   
        sed -i 's/\(^\s*\)-/-&/' tfplan_short

        plan=$(cat tfplan_short)

        cat > message.md << EOF
        The Terraform configuration changes resulted with the following [plan]($TERRAFORM_PLAN_ARTIFACT_LINK).

        ### Plan summary  
        \`\`\`diff
        + 0 to add ✅
        ! 1 to change 🔀
        - 0 to destroy 💥
        \`\`\`

        <details>
          <summary>Detailed plan output:</summary>

        \`\`\`diff
        $plan
        \`\`\`

        </details>
        EOF

      env:
        TERRAFORM_PLAN_FILE_NAME: ${{ inputs.terraform-plan-file-name }}
        TERRAFORM_PLAN_ARTIFACT_LINK: ${{ inputs.terraform-plan-artifact-link }}

    - name: Add pull request comment with Terraform plan
      uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2.8.2
      with:
        message-path: message.md
        message-id: terraform-plan
        message-failure: |-
          We had some issues formatting the plan for you, 
          but you can still see it using this [link](${{ inputs.terraform-plan-artifact-link }})
